#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
"""Generate the per-audience schema/visibility matrix for one grounding database.

One row per table, one column per audience, so "who can see what" is a reviewable artifact instead
of tribal knowledge. Read-only: every fact comes from `rc project database preview` (which mints the
same scoped views a real run gets) and, when the installed `rc` supports per-principal schema reads,
`rc dev console database schema`.

    scope_matrix.py --project kampadmin --dsn KAMPADMIN_APP_DSN --tenant acme \
        --as regular-admin=kampadmin_person:<uuid> \
        --as parent=kampadmin_parent:<uuid> \
        --out _internal/scope-matrix-app.md

The `no-principal` audience is always included and is the reference column: every other column reads
as "what this identity loses relative to the tenant-wide view".
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from scope_common import (  # noqa: E402
    Audience,
    RcError,
    audiences_from_specs,
    rc_json,
    scope_flags,
    unsupported_flag,
)

VISIBLE = "✓"
HIDDEN = "hidden"
ABSENT = "—"


def preview(project: str, dsn: str, tenant: str | None, aud: Audience, timeout: int) -> dict:
    """`rc project database preview` for one audience — the one real per-identity projection."""
    return rc_json(
        ["project", "database", "preview", dsn, *scope_flags(project, tenant), *aud.flags()],
        timeout=timeout,
    )


def schema_columns(project: str, db: str, tenant: str | None, aud: Audience, timeout: int):
    """``{table: [column, ...]}`` for one audience, or ``None`` when this `rc` cannot scope a schema
    read by principal (older CLI). Column stripping is then simply omitted — the table matrix, which
    is the load-bearing half, still renders."""
    try:
        payload = rc_json(
            ["dev", "console", "database", "schema", db, *scope_flags(project, tenant), *aud.flags()],
            timeout=timeout,
        )
    except RcError as err:
        if aud.is_principal and unsupported_flag(err, "--principal-kind"):
            return None
        raise
    out = {}
    for table in payload.get("tables") or []:
        name = table.get("name")
        if name:
            out[name] = [c.get("name") for c in (table.get("columns") or []) if c.get("name")]
    return out


def classify(report: dict) -> dict[str, str]:
    """One preview report → ``{table: cell}``.

    `hidden` beats everything (it is the permission boundary we came for); a table with a compiled
    predicate is row-constrained and shows its count, so a reviewer sees "sees 3 of 4000 rows" and
    not just a checkmark.
    """
    cells = {t: HIDDEN for t in report.get("hidden_tables") or []}
    unconstrained = set(report.get("unconstrained_tables") or [])
    # Unconstrained tables are minted views with no extra predicate — the preview lists them by name
    # only, so they must become ✓ here or the whole tenant-wide column reads as "not in projection".
    for name in unconstrained:
        cells.setdefault(name, VISIBLE)
    for table in report.get("tables") or []:
        name = table.get("name")
        if not name or name in cells:
            continue
        predicate = (table.get("predicate") or "").strip()
        if predicate and name not in unconstrained:
            cells[name] = f"rows:{table.get('count', '?')}"
        else:
            cells[name] = VISIBLE
    return cells


def grants_line(report: dict) -> str:
    grants = report.get("table_grants") or {}
    if grants.get("all"):
        return "all tables"
    granted = grants.get("granted") or []
    return f"{len(granted)} table(s): {', '.join(sorted(granted))}" if granted else "none"


def _escape(cell: str) -> str:
    return cell.replace("|", "\\|")


def render(
    *,
    project: str,
    dsn: str,
    tenant: str | None,
    audiences: list[Audience],
    reports: dict[str, dict],
    columns: dict[str, dict | None],
    command: str,
    generated_at: str,
) -> str:
    cells = {a.label: classify(reports[a.label]) for a in audiences}
    all_tables = sorted({t for per in cells.values() for t in per})

    lines = [
        f"# Scope matrix — {project} / {dsn}",
        "",
        f"- Project: `{project}`",
        f"- Database: `{dsn}`",
        f"- Tenant: `{tenant or '(none — flat/cross-tenant preview)'}`",
        f"- Generated: {generated_at}",
        f"- Regenerate: `{command}`",
        "",
        "Generated by the `scope-check` skill from `rc project database preview` — the same scoped",
        "views a real run of that identity gets. Do not hand-edit; regenerate and commit the diff.",
        "",
        f"`{VISIBLE}` = fully queryable · `rows:<n>` = row-constrained by a compiled predicate "
        f"(n rows visible) · `{HIDDEN}` = removed by the access policy (raises "
        f"`lib.db.HiddenTableError`) · `{ABSENT}` = not in this projection at all",
        "",
    ]

    header = "| table | " + " | ".join(a.label for a in audiences) + " |"
    lines += [header, "|" + "---|" * (len(audiences) + 1)]
    for table in all_tables:
        row = [_escape(cells[a.label].get(table, ABSENT)) for a in audiences]
        lines.append(f"| `{table}` | " + " | ".join(row) + " |")

    lines += ["", "## Table grants", ""]
    for aud in audiences:
        lines.append(f"- **{aud.label}** — {grants_line(reports[aud.label])}")

    lines += ["", "## Columns stripped vs `no-principal`", ""]
    baseline = columns.get("no-principal")
    reported = False
    for aud in audiences:
        if not aud.is_principal:
            continue
        theirs = columns.get(aud.label)
        if baseline is None or theirs is None:
            continue
        reported = True
        stripped = []
        for table in sorted(baseline):
            missing = sorted(set(baseline[table]) - set(theirs.get(table, [])))
            if missing and table in theirs:  # a wholly absent table is a table-level fact, not columns
                stripped.append(f"  - `{table}`: {', '.join(f'`{c}`' for c in missing)}")
        lines.append(f"- **{aud.label}**" + ("" if stripped else " — none"))
        lines += stripped
    if not reported:
        lines.append(
            "_Not available: this `rc` cannot scope a schema read by principal "
            "(`rc dev console database schema --principal-kind`). Upgrade `rc` and regenerate._"
        )
    lines.append("")
    return "\n".join(lines)


def build_command(args) -> str:
    parts = ["scope_matrix.py", "--project", args.project, "--dsn", args.dsn]
    if args.tenant:
        parts += ["--tenant", args.tenant]
    for spec in args.audience or []:
        parts += ["--as", spec]
    if args.out:
        parts += ["--out", args.out]
    return " ".join(parts)


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--project", required=True)
    p.add_argument("--dsn", required=True, help="DSN env var name, e.g. KAMPADMIN_APP_DSN")
    p.add_argument("--tenant", help="tenant slug; omit for the flat/cross-tenant preview")
    p.add_argument(
        "--as",
        dest="audience",
        action="append",
        metavar="LABEL=KIND:EXTERNAL_ID",
        help="repeatable; no-principal is always included",
    )
    p.add_argument("--out", help="write markdown here (default: stdout)")
    p.add_argument("--timeout", type=int, default=180, help="per-rc-call timeout in seconds")
    p.add_argument("--no-columns", action="store_true", help="skip the per-audience schema reads")
    args = p.parse_args(argv)

    try:
        audiences = audiences_from_specs(args.audience)
    except ValueError as exc:
        p.error(str(exc))

    reports: dict[str, dict] = {}
    columns: dict[str, dict | None] = {}
    try:
        for aud in audiences:
            reports[aud.label] = preview(args.project, args.dsn, args.tenant, aud, args.timeout)
            if not args.no_columns:
                columns[aud.label] = schema_columns(
                    args.project, args.dsn, args.tenant, aud, args.timeout
                )
    except RcError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    md = render(
        project=args.project,
        dsn=args.dsn,
        tenant=args.tenant,
        audiences=audiences,
        reports=reports,
        columns=columns,
        command=build_command(args),
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )
    if args.out:
        path = Path(args.out)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(md)
        print(f"wrote {path} ({len(md.splitlines())} lines)")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
